[[plugins]]
name = "app_launcher"
description = "Launch applications based on your desktop environment."
prefix = ""
picker = "python ~/.config/fzfmenu/plugins/app_launcher.py picker"
runner = "python ~/.config/fzfmenu/plugins/app_launcher.py runner"
background = true

[[plugins]]
name = "killer"
description = "Find and terminate running processes."
prefix = "kl "
picker = "python ~/.config/fzfmenu/plugins/killer.py picker"
runner = "python ~/.config/fzfmenu/plugins/killer.py runner"
dynamic = true
background = true

[[plugins]]
name = "ura-jumper"
description = "Jump to any windows (only works on Ura WM)."
prefix = "wd "
picker = "python ~/.config/fzfmenu/plugins/ura-jumper.py picker"
runner = "python ~/.config/fzfmenu/plugins/ura-jumper.py runner"
background = true

[[plugins]]
name = "ura-move"
description = "move any windows to current workspace (only works on Ura WM)."
prefix = "wi "
picker = "python ~/.config/fzfmenu/plugins/ura-move.py picker"
runner = "python ~/.config/fzfmenu/plugins/ura-move.py runner"
on_enter = ["change-multi"]
on_leave = ["change-multi(0)"]
background = true

[[plugins]]
name = "ura-tag"
description = "Enable or create new tags"
prefix = "wg "
picker = "python ~/.config/fzfmenu/plugins/ura-tag.py picker"
runner = "python ~/.config/fzfmenu/plugins/ura-tag.py runner"
dynamic = true
background = true

[[plugins]]
name = "ura-selector"
description = "Select existing tags"
prefix = "ws "
picker = "python ~/.config/fzfmenu/plugins/ura-selector.py picker"
runner = "python ~/.config/fzfmenu/plugins/ura-selector.py runner"
dynamic = true
background = true

[[plugins]]
name = "brotab"
description = "Activate tab using brotab"
prefix = "fx "
picker = "python ~/.config/fzfmenu/plugins/brotab.py picker"
runner = "python ~/.config/fzfmenu/plugins/brotab.py runner"
background = true

[[plugins]]
name = "history"
description = "Search and reuse past shell commands."
prefix = "hs "
picker = "python ~/.config/fzfmenu/plugins/history.py picker"
runner = "python ~/.config/fzfmenu/plugins/history.py runner"
dynamic = true

[[plugins]]
name = "sink"
description = "Switch default pipewire sink."
prefix = "sk "
picker = "python ~/.config/fzfmenu/plugins/sink.py picker"
runner = "python ~/.config/fzfmenu/plugins/sink.py runner"
background = true

[[plugins]]
name = "mpris"
description = "control play/pause with playerctl."
prefix = "mp "
picker = "python ~/.config/fzfmenu/plugins/mpris.py picker"
runner = "python ~/.config/fzfmenu/plugins/mpris.py runner"
background = true

[[plugins]]
name = "sing-box"
description = "manage sing-box user service."
prefix = "sb "
picker = "python ~/.config/fzfmenu/plugins/sing-box.py picker"
runner = "python ~/.config/fzfmenu/plugins/sing-box.py runner"
on_enter = [
  "change-preview(systemctl --user status sing-box.service)",
  "show-preview",
]
on_leave = ["hide-preview"]
background = true
