- name: apply dotfiles
  hosts: local
  tasks:
    - name: Apply user-level dotfiles
      command: stor -f user/*/
      register: result

    - name: Show output
      debug:
        msg: "{{ result.stdout }}"

    - name: Apply system-level dotfiles
      command: stor -cft / system/*/
      become: true
      register: result

    - name: Show output
      debug:
        msg: "{{ result.stdout }}"
